//常用的HTML
var arrHTML=new Array()
//右边的按钮
arrHTML['rightbuttons']			='<table width="100%"  border="0" cellpadding="0" cellspacing="0">'
								+'<tr>'
								+'<td align="center" height="28"><input id="btOK" type="button" class="dialogRightButton" value="确定" onClick="doOK()"></td>'
								+'</tr>'
								+'<tr>'
								+'<td align="center" height="28"><input id="btCancel" type="button" class="dialogRightButton" value="取消" onClick="closeDialog()"></td>'
								+'</tr>'
								+'</table>'
//可编辑的下拉框					
arrHTML['editableselect']		='<div style="position: absolute;width:<WIDTH>;height:100%;" class="longWidth"><table width="100%"  border="0" cellspacing="0" cellpadding="0"><tr>'
								+'<td width="100%"><iframe id="ifrm<NAME>" style="	position:absolute;margin: 0px;border: none; top:2px;left:2px;height:16px;width:100%" scrolling="no" frameborder="0"></iframe></td>'
								+'<td width=21 valign="top"><img width=21 height=1></td></tr></table></div>'
								+'<select id="slt<NAME>" ifrmId="ifrm<NAME>" class="longWidth"  editable="true"  style="width:<WIDTH>;height:20px;"  onChange="doEditableSelectChange();"><OPTIONS></select>'

//下拉框
arrHTML['select']				='<select id="slt<NAME>" style="width:<WIDTH>;"><OPTIONS></select>'
//样式表/其它
arrHTML['css/other']			='<table id="tblCssOther" style="display:none" width="100%"  border="0" cellpadding="0" cellspacing="1"><tr>'
								+'<tr>'
								+'<td width=80 height="22" align="right">访问键:</td>'
								+'<td><input type="text" class="shortWidth" id="tfAccessKey" maxlength="1"></td>'
								+'</tr>'
								+'<tr>'
								+'<td height="22" align="right">Tab 索引键:</td>'
								+'<td><input type="text" class="shortWidth" id="tfTabIndex" restrict="0-9" onKeyPress="doRestrict()" onKeyUp="doRestrict()" onChange="doRestrict()"></td>'
								+'</tr>'
								+'<tr>'
								+'<td height="22" align="right">ID:</td>'
								+'<td><input type="text" class="normalWidth" id="tfId"></td>'
								+'</tr>'
								+'<tr>'
								+'<td height="22" align="right">标题:</td>'
								+'<td><input id="tfTitle" type="text" class="longWidth" ></td>'
								+'</tr>'
								+'<tr>'
								+'<td height="22" align="right">类:</td>'
								+'<td>'
								+arrHTML['editableselect'].replace(/<NAME>/g,'Class').replace(/<WIDTH>/g,'120px')
								+'</td>'
								+'</tr>'
								+'<tr valign="top">'
								+'<td height="22" align="right">样式:</td>'
								+'<td valign="top"><table width="100%"  border="0" cellpadding="0" cellspacing="0">'
								+'<tr>'
								+'<td width="1" valign="top"><textarea rows="6" wrap="OFF" class="longWidth" id="taStyle"></textarea></td>'
								+'<td valign="top"><img height=0 width=0>\n'
								+'<input type="button" value="编辑" style="height:20px" onClick="showStyleEditor()"></td>'
								+'</tr>'
								+'</table></td>'
								+'</tr></table>'
//颜色格
arrHTML['color']				='<table width="100%" border="0" cellpadding="0" cellspacing="0">'
								+'<tr>' 
								+'<td width="16"><img src="<PATH>btColor.gif" class="overBorder" onClick="getAndSetColor(null,null,\'obj.style.backgroundColor=obj.parentNode.parentNode.lastChild.firstChild.value=obj.parentNode.parentNode.lastChild.firstChild.hiddenValue=ifrmColorPicker.document.all.tfHexColor.value;<EXTRASCRIPT_0>\')"  onMouseDown="this.className=\'upBorder\'" onMouseUp="this.className=\'overBorder\'"></td>'
								+'<td width="3"><img width=3 height=1></td>'
								+'<td><input id="tf<NAME>" type="text" class="tfColor" restrict="#0-9A-Fa-f" onKeyPress="doRestrict();if(event.keyCode==13){doTfHexChange();<EXTRASCRIPT>}" onKeyUp="doRestrict()" onChange="doRestrict();doTfHexChange();<EXTRASCRIPT>" maxlength="7"></td>'
								+'</tr>'
								+'</table>'

//文件浏览
arrHTML['file']					='<table width="100%" border="0" cellpadding="0" cellspacing="0">'
								+'<tr>' 
								+'<td width="1">'
								+arrHTML['editableselect']
								+'</td><td><img width=1 height=1>\n\r<input type="button" value="浏览" style="height:20px" onclick="showExplorer()">'
								+'</td></tr></table>'
//数字与单位
arrHTML['digitalunits']			='<input id="tf<NAME>" value="<VALUE>" type="text" class="shortWidth"  restrict="\-0-9" onKeyPress="doRestrict()" onKeyUp="doRestrict()" onChange="doRestrict()"  style="width:<WIDTH>;">\n\r'
								+'<select id="<NAME>Units">'
								+'<option value="%">%</option>'
								+'<option value="" selected>像素</option>'
								+'</select>'

//数字
arrHTML['digital']				='<input id="tf<NAME>" value="<VALUE>"  type="text" class="shortWidth" onChange="doRestrict()" onKeyPress="doRestrict()" onKeyUp="doRestrict()"  restrict="\-0-9"  style="width:<WIDTH>;">'
//对齐
arrHTML['halign']				='<select id="slt<NAME>"  style="width:<WIDTH>;">'
								+'<option>默认</option>'
								+'<option value="left">左对齐</option>'
								+'<option value="Center">居中</option>'
								+'<option value="Right">右对齐</option>'
								+'<option value="justify">(两端对齐)</option>'
								+'</select>'
arrHTML['valign']				='<select id="slt<NAME>"  style="width:<WIDTH>;">'
								+'<option>默认</option>'
								+'<option value="Baseline">基线</option>'
								+'<option value="Top">顶端</option>'
								+'<option value="Middle">居中</option>'
								+'<option value="Bottom">底部</option>'
								+'<option value="TextTop">文本顶</option>'
								+'<option value="AbsMiddle">绝对居中</option>'
								+'<option value="AbsBottom">绝对靠底</option>'
								+'</select>'
arrHTML['align']				='<select id="slt<NAME>"  style="width:<WIDTH>;">'
								+'<option>默认</option>'
								+'<option value="Baseline">基线</option>'
								+'<option value="Top">顶端</option>'
								+'<option value="Middle">居中</option>'
								+'<option value="Bottom">底部</option>'
								+'<option value="TextTop">文本顶</option>'
								+'<option value="AbsMiddle">绝对居中</option>'
								+'<option value="AbsBottom">绝对靠底</option>'
								+'<option value="left">左对齐</option>'
								+'<option value="Center">居中对齐</option>'
								+'<option value="Right">右对齐</option>'
								+'</select>'
//复选框
arrHTML['chk']					='<input id="chk<NAME>" value="<VALUE>"  type="checkbox">'
//单选框
arrHTML['rd']					='<input id="rd<NAME>" value="<VALUE>" name="<GROUP>" type="radio">'
//文本段
arrHTML['txt']					='<input id="tf<NAME>" value="<VALUE>"  type="text" class="normalWidth">'
arrHTML['longtxt']				='<input id="tf<NAME>" value="<VALUE>"  type="text" class="longWidth">'
arrHTML['shorttxt']				='<input id="tf<NAME>" value="<VALUE>"  type="text" class="shortWidth">'
//文本域
arrHTML['textarea']					='<textarea id="ta<NAME>" rows="8" style="width:100%"  style="width:<WIDTH>;"></textarea>'
//字体
arrHTML['font']					='<select id="slt<NAME>"  style="width:<WIDTH>;">'
								+'<option value="">默认字体' 
								+'<option value="宋体">宋体' 
								+'<option value="黑体">黑体' 
								+'<option value="楷体_GB2312">楷体' 
								+'<option value="仿宋_GB2312">仿宋' 
								+'<option value="隶书">隶书' 
								+'<option value="幼圆">幼圆' 
								+'<option value="新宋体">新宋体' 
								+'<option value="细明体">细明体' 
								+'<option value="Arial">Arial' 
								+'<option value="Arial Black">Arial Black' 
								+'<option value="Arial Narrow">Arial Narrow' 
								+'<option value="Bradley Hand ITC">Bradley Hand ITC' 
								+'<option value="Brush Script MT">Brush Script MT' 
								+'<option value="Century Gothic">Century Gothic' 
								+'<option value="Comic Sans MS">Comic Sans MS' 
								+'<option value="Courier">Courier' 
								+'<option value="Courier New">Courier New' 
								+'<option value="Geneva">Geneva' 
								+'<option value="Impact">Impact' 
								+'<option value="MS Sans Serif">MS Sans Serif' 
								+'<option value="Optima">Optima' 
								+'<option value="Script">Script' 
								+'<option value="System">System' 
								+'<option value="Times">Times' 
								+'<option value="Times New Roman">Times New Roman' 
								+'<option value="Viner Hand ITC">Viner Hand ITC' 
								+'<option value="Verdana">Verdana' 
								+'<option value="Wide Latin">Wide Latin' 
								+'<option value="Wingdings">Wingdings</option>'
								+'</select>'